default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: car_maintenance_reminder_development

test:
  <<: *default
  database: car_maintenance_reminder_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>